### ISSUE TITLE
梆梆加固的解不了

### ISSUE THREAD

**Issue by kjsolo** [DrizzleRisk/BUnpacker#2]
[>>>]       BUnpacker         [<<<]
[>>>]    code by Drizzle      [<<<]
[>>>]        2016.10          [<<<]
[*] Init env
[*] Target: armeabi
[---------------------------------------]
[---------------------------------------]
[*] Get package info
[*] Dump dex

一直卡在这个地方重试了很多次

**Comment by DrizzleRisk** [comment]
程序不是针对梆梆加固的
